### PR TITLE
Rapanui multilayer support (RNLayer)

### PR DESCRIPTION
**Pull request by vertti**
Fixes issue #59

This pull request contains:
- RNLayer to handle multilayer games
- rapanui-test folder that contains unit tests for all the new features
- rapanui-test/lunatest which contains a copy of LunaTest unit testing framework

The unit tests included will hopefully show it's pretty easy to write tests for Rapanui components and encourage others to also commit code with unit tests.

### CODE REVIEW

**Comment by MattiaFortunati** [comment]
Hi guys,
thanks for this pull request!

But, can I ask you to split this pull request in two different ones?
One for the multilayer implementation and the other for the unit tests, so I can merge and test them better, and in different moments.

Thanks

**Comment by vertti** [comment]
Hi,

To see how the multilayer works, see the tutorial that was added under "rapanui-samples/multilayer".
To check the unit tests, you can just run any of the files in the rapanui-test folder that ends with Test, like

```
lua RNLayerTest.lua
```

I don't think it's possible with those commits and in general it's not a good idea to try to split the implementation and it's unit tests to two pulls, because you should always write them together at the same time.

**Comment by MattiaFortunati** [comment]
I agree, 

but I see multilayer and unit test implementation as two different features.
It's just I wanted to merge layers first and unit tests when I have much time to review them, since unit tests have different priority at the moment.

Also, we have to discuss about the use of lunatest, so I wanted to merge layers first, and then think about adding lunatest into RapaNui, while this commit forces me to do both things at the same time.

**Comment by niom** [comment]
Sorry I do not agree that unit tests and implementation should be splitted in different commits. You have to be sure that when you create a new feature it doesn't break any old features (Regression tests) and also you are sure that the new feature does what you wanted it to do (TDD). Releasing features without tests or with test after is against my view of good practise and I will not release any features without proper tests.

From my point of view the unit tests are more important than the multilayer feature. Unit tests will save us much more time from bugs and will make future reviews much more easier when you don't have to figure out if old features are broken by the new commits.

Unit tests are even more important with open source projects when you have multiple developers and cannot be sure what kind of code they produce.

**Comment by eljeko** [comment]
Hi,

First of all I want to thank you for the great work, specially on unit testing.

I totally agree about unit testing, but we are asking to split the pull to make easier for us to work on it: that's all :)

I'll talk with Mattia on how to handle this.

thank you,
Stefano

**Pull request merged**
