### PR TITLE
RNDirector 

### PR DESCRIPTION
**Pull request by ghost**
I have made some changes to RNDirector which I think you should look at.

The other files you may want to look at since they are there.
(sorry that a lot of files have been included. I can't for the life of me figure out how to stop it.)

### CODE REVIEW

**Comment by eljeko** [comment]
We are completely rewriting RNDirector, very good suggestions anyway.
Also the other pulled code it's very interesting and contains useful things, thanks a lot! 
We are very busy on internal project but I'll check your pull better next days.

**Comment by ghost** [comment]
I saw the notification eljeko.

I used:
             (RNFactory.lua)
 MOAISim.openWindow(name, SW, SH)
 screen:initWith(PW, PH, SW, SH )
             (RNScreen.lua)
 self.viewport:setSize(SW, SH)

to get the viewport to scale the project to real size (to an ipad) as I got annoyed at having 1024px program on my computer monitor.

I am not sure if the outcome would look like what I am developing with. I will have to check (getting myself a macbook for christmas) soon. I also don't know what'll happen when I run the code from device, does it ignore the  MOAISim.openWindow() function?

**Comment by eljeko** [comment]
thanks I'll keep you up to date

**Comment by eljeko** [comment]
Hi,

Check out the new Director that includes some of your suggestions.

Next days I'll also check the code for managing the screen size,

If you can give us some feedback

**Comment by eljeko** [comment]
Merged your code for shape and some suggestion on RNDirector!

thank you very much!

**Pull request closed without merging**
