### PR TITLE
Added global scissor rectangle for scenes handled by RNDirector

### PR DESCRIPTION
**Pull request by Sylph**
globalScissorRect is moved with the scene if it's being swapped out through slide.

### CODE REVIEW

**Comment by Sylph** [comment]
For https://github.com/ymobe/rapanui/issues/74

**Comment by MattiaFortunati** [comment]
Hi, 

So your code sets a scissor rect to scene group which will also moves with transitions. 
It seems pretty good to fix point 2 of issue #74. (I've updated that issue :D)

I'll merge this asap.

**Comment by Sylph** [comment]
I believe it also cover point 1 unless you're thinking of something else. However, it does have the drawback/bug that it get overwritten by newly set scissorRectangles, which is probably not what we want?. I'm not sure how we'd want to handle that, unless:
1. we add the ability to let us set multiple scissor Rect on Moai source
2. move all newly/manually set scissor Rectangle recursively as well.

There's also a problem with the following part when you're not letterboxed:

```
        self:slideout(RNFactory.outWidth, 0)
    elseif effect == "slidetoright" then
        self:slideout(-RNFactory.outWidth, 0)
    elseif effect == "slidetotop" then
        self:slideout(0, RNFactory.outHeight)
    elseif effect == "slidetobottom" then
        self:slideout(0, -RNFactory.outHeight)
```

may want to replace RNFactory.outWidth/RNFactory.outHeight  with RNFactory.screenUnitsX/RNFactory.screenUnitsY, so that the slide happen for the right length.

**Comment by MattiaFortunati** [comment]
> I believe it also cover point 1 unless you're thinking of something else.

Point 1 is about a global scissorRect to be there also if RNDirector is not used.

> However, it does have the drawback/bug that it get overwritten by newly set scissorRectangles, which is probably not what we want?. I'm not sure how we'd want to handle that, unless:
> 1. we add the ability to let us set multiple scissor Rect on Moai source
> 2. move all newly/manually set scissor Rectangle recursively as well.

yes, you are right. 
This will be definitely a problem for RNDirector scissor rect.

> may want to replace RNFactory.outWidth/RNFactory.outHeight with RNFactory.screenUnitsX/RNFactory.screenUnitsY, so that the slide happen for the right length.

This is a problem, too, since you may not use letterbox.

Thanks for investigating in this mechanics with me ^^, I'll try to keep updated the issue #74

**Comment by MattiaFortunati** [comment]
Ok, 

I'll close this for the moment.
Check #74.

I've split issues.

**Pull request closed without merging**
